spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active:
      - production
jwt.secret: my-app-secret
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://localhost:3306/myDB
    username: root
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update